server:
  port: 3366
spring:
  application:
    name: cloud-config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/lovehzy/cloud-config.git  #GitHub上面的git仓库名字